name: Build and Test

on:
  # Run when pushing to stable branches
  push:
    branches:
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

env:
  elixir_version: "1.12.3"
  otp_version: "24.1"

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-${{ env.elixir_version }}-${{ env.otp_version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-_build-${{ env.otp_version }}-${{ env.elixir_version }}
    - uses: erlef/setup-elixir@v1.7.0
      with:
        otp-version: ${{ env.otp_version }}
        elixir-version: ${{ env.elixir_version }}
    - name: Install Dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Compile
      run: mix compile
    - name: Test and Coverage
      run: mix coveralls.github
